# Generated by Django 2.1.15 on 2020-05-29 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statement', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('contracts', '0001_initial'),
        ('dict_register', '0002_auto_20200529_0956'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('l_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageproperty',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stageproperty_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stageproperty_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='registertemplatedocument',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registertemplatedocument_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registertemplatedocument',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registertemplatedocument_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registertemplatedocument',
            name='group_template',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='dict_register.TemplateDocument', verbose_name='Група шаблонів'),
        ),
        migrations.AddField(
            model_name='registertemplatedocument',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='act',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.RegisterAct', verbose_name='Акт'),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registerpayment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registerpayment_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='importer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.ImportPayment', verbose_name='Назва завантаження'),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='registeract',
            name='accrual',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.RegisterAccrual', verbose_name='Нарахування'),
        ),
        migrations.AddField(
            model_name='registeract',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeract_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeract',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='registeract',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeract_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeract',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='registeraccrual',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeraccrual_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeraccrual',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='registeraccrual',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeraccrual_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeraccrual',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='payplan',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payplan_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payplan',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='payplan',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payplan_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payplan',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='importpayment',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importpayment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importpayment',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importpayment_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importpayment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='coordination',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordination_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordination',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='coordination',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordination_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordination',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractsubscription_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract'),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractsubscription_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict_register.Subscription'),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractproducts_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract'),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractproducts_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict_register.Product'),
        ),
        migrations.AddField(
            model_name='contractfinance',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractfinance_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractfinance',
            name='contract',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='contractfinance',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractfinance_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractfinance',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_contractor', to='l_core.CoreOrganization', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Батьківський елемент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statement.SEDStatement', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='accrual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.RegisterAccrual'),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualsubscription_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualsubscription_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict_register.Subscription'),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='accrual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.RegisterAccrual'),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualproducts_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualproducts_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.CoreOrganization'),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict_register.Product'),
        ),
    ]
